name: cellprofiler-core425

channels:
- ome
- conda-forge
- bioconda
- anaconda
- defaults

dependencies:
- python=3.8
- pip
- omero-py
- jupyter
#- javabridge
- h5py
#- cudatoolkit=11.8.0
- matplotlib
#- pandas
#- mysqlclient
#- openjdk
- imageio
#- scikit-learn
- scikit-image
- scipy
- scyjava
#- six
#- mahotas
#- gtk2
#- Jinja2=3.0.1
#- inflect=5.3.0
- wxpython=4.1.0
- centrosome
#- mysqlclient=1.4.4
#- sentry-sdk=0.18.0
- pip:
#    - centrosome
#    - ome-zarr
#    - ome-cli-zarr
    - numpy
    - pandas
#    - cellprofiler-core==4.2.5
    - cellprofiler==4.2.5
    - ezomero
    - omero-rois
    - omero-upload
    - omero-metadata
    - omero-cli-duplicate
#    - omero-marshal
#    - cellpose==2.1.0
#    - stardist
#    - csbdeep
#    - omnipose
#    - imagej==0.3.1
#    - pyjnius==1.4.1
#    - tensorflow==2.12.*
#    - nvidia-cudnn-cu11==8.6.0.163
