name: cp4

channels:
- conda-forge
- anaconda
- bioconda
- defaults

dependencies:
- python=3.8
- pip
- omero-py
#- cudatoolkit=11.8.0
- numpy==1.23.0
- matplotlib
- pandas
- mysqlclient
- openjdk
- imageio
- scikit-learn
- scikit-image
- scipy
- six
- mahotas
- gtk2
- Jinja2=3.0.1
- inflect=5.3.0
- wxpython=4.1.0
- mysqlclient=1.4.4
- sentry-sdk=0.18.0
- pip:
    - ome-zarr
    - cellprofiler==4.2.4
    - cellpose==2.1.0
    - stardist
    - csbdeep
    - omnipose
    - imagej==0.3.1
    - pyjnius==1.4.1
#    - tensorflow==2.12.*
#    - nvidia-cudnn-cu11==8.6.0.163
