name: cellprofiler-core425

channels:
- ome
- conda-forge
- bioconda
- anaconda
- defaults

dependencies:
- python=3.8
- pip
- omero-py
- jupyter
- h5py
- matplotlib
- imageio
- scikit-image
- scipy
- scyjava
- wxpython=4.1.0
- centrosome
- pip:
    - numpy
    - pandas
#    - cellprofiler-core==4.2.5
    - cellprofiler==4.2.5
    - ezomero
    - omero-rois
    - omero-upload
    - omero-metadata
    - omero-cli-duplicate
